print("Введіть значення a, а не дорівнює нулю")
a=int(input())
print("Введіть значення b")
b=int(input())
print("Введіть значення c")
c=int(input())
x1=(-b+(b**2-4*a*c)**0.5)/(2*a)
x2=(-b-(b**2-4*a*c)**0.5)/(2*a)
print("x1 =",x1)
print("x2 =",x2)
input()